# **Projeto Terra Signal - Telecomunicações**

## **Entendimento do problema**

Como estruturar, processar, armazenar
e disponibilizar de forma segura os dados
da Terra Signal, para que possam ser utilizados
em análises capazes de apoiar a compreensão
de sua carteira de clientes?

- **Objetivo Geral**

Desenvolver uma solução integrada
para estruturar, processar, armazenar
e analisar os dados da Terra Signal,
utilizando a Arquitetura Medalhão e técnicas
de análise exploratória, de modo a produzir
informações confiáveis que apoiem a
compreensão de sua carteira de clientes.

- **Base de dados**

A Terra Signal é uma empresa fictícia do setor
de telecomunicações. A base history.csv,
disponibilizada pela Databricks, contém
informações sobre sua carteira histórica de clientes,
incluindo características individuais, serviços
contratados, relacionamento, informações financeiras
e histórico de cancelamento.

- **Variáveis da Base**

- *Cliente*
    - customerID: ID do cliente;
    - gender: Gênero;
    - SeniorCitizen: É idoso?;
    - Partner: É parceiro?;
    - Dependents: Tem dependentes?;

- *Relacionamento*
    - Tenure: A duração da posse.

- *Serviços*
    - PhoneServico: Serviço Telefonico - Possui?;
    - MultipleLines: Múltiplas linhas - Possui?;
    - InternetService: Serviço de internet;
    - OnlineSecurity: Segurança Online;
    - OnlineBackup: JBackup Online;
    - DeviceProtection: Proteção do dispositivo;
    - TechSupport: Suport técnico;
    - StreamingTV: Streaming na TV;
    - StreamingMovies: Filmes no streaming.

- *Contrato e Pagamento*
    - Contract: Contrato;
    - PaperlessBilling: Faturamento sem papel (Cobrança digital);
    - PaymentMethod: Método de pagamento.

- *Financeiro*
    - MonthlyCharges: Cobranças mensais;
    - TotalCharges: Cobranças totais;
    - MonthlyIncome: Renda mensal.

- *Experiência e Cancelamento*
    - CustomerFeedback: Feedback do cliente;
    - Churn: Taxa de cancelamento.

## **Etapas do Projeto**:

### **Camada Bronze**

#### **Dados**

##### **Instalação das Bibliotecas**

In [1]:
# %pip install pandas

In [2]:
# %pip install statistics

##### **Importação das bibliotecas**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as st

##### **Importação da Base**

In [4]:
df = pd.read_csv("../Data/Raw/history.csv")

#### **Exploração inicial**

- Função de análise

In [5]:
def analise_inicial(df):
    print("Informações do DataFrame:")
    display(df.info())
    print("\nEstatísticas descritivas:")
    display(df.describe())
    print("\nValores nulos por coluna:")
    display(df.isnull().sum())
    print("\nValores Duplicados por coluna:")
    display(df.duplicated().sum())
    print("\nNúmero de linhas e colunas:")
    display(df.shape)

In [6]:
analise_inicial(df)

Informações do DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   str
 1   gender            5634 non-null   str
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   str
 4   Dependents        5634 non-null   str
 5   tenure            5634 non-null   str
 6   PhoneService      5634 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), str(19)
memory usage: 1012.5 KB

None

Estatísticas descritivas:

       SeniorCitizen  MonthlyCharges  TotalCharges  MonthlyIncome
count    5634.000000     5634.000000   5356.000000    5634.000000
mean        0.164714       64.609523   2271.883150    5104.879304
std         0.370955       30.152186   2253.784765    2839.230500
min         0.000000       18.400000     18.800000     100.000000
25%         0.000000       35.162500    412.900000    2693.750000
50%         0.000000       70.300000   1390.725000    5079.500000
75%         0.000000       89.800000   3729.750000    7574.750000
max         1.000000      118.650000   8684.800000    9993.000000

Valores nulos por coluna:

customerID            0
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges        278
Churn                 0
CustomerFeedback      0
MonthlyIncome         0
dtype: int64

Valores Duplicados por coluna:

np.int64(0)

Número de linhas e colunas:

(5634, 23)

In [7]:
df.head(15)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691
5,6797-LNAQX,Male,0,Yes,Yes,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Two year,No,Bank transfer (automatic),98.30,6859.50,Yes,I have been a customer with this company for 7...,5487
6,3050-GBUSH,Female,0,No,No,3,no,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Credit card (automatic),34.80,113.95,No,I have been a customer with this DSL internet ...,6382
7,8020-BWHYL,Female,1,No,No,15,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Credit card (automatic),75.30,NaN,Yes,I recently canceled my service with this provi...,353
8,6752-APNJL,Male,0,Yes,Yes,42,Yes,No,DSL,Yes,...,No,No,Month-to-month,No,Mailed check,54.50,2301.15,No,I have been a customer with this company for 4...,2436
9,1760-CAZHT,Male,0,No,Yes,25,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Mailed check,20.80,460.20,No,I have been a customer with this company for 2...,7049
10,3070-FNFZQ,Female,0,Yes,Yes,23,Yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Bank transfer (automatic),20.40,478.75,No,I have been a customer with this company for 2...,4625
11,4452-QIIEB,Male,0,No,No,7,Yes,No,DSL,No,...,No,No,Month-to-month,No,Mailed check,43.90,278.40,No,I have been a customer with this DSL internet ...,1204
12,7767-UXAGJ,Male,0,No,No,1,Yes,Yes,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,50.45,50.45,Yes,I recently signed up for DSL internet service ...,5388
13,9793-WECQC,Male,0,No,No,23,Yes,No,Fiber optic,No,...,Yes,Yes,Month-to-month,No,Mailed check,95.30,2192.90,No,I have been a customer with this company for a...,6643
14,7029-IJEJK,Female,0,No,No,54,No,No phone service,DSL,Yes,...,No,Yes,One year,No,Bank transfer (automatic),44.10,2369.70,No,I have been a loyal customer of this DSL inter...,5176

#### **Discussão Inicial - Análise de Variáveis**

Inicialmente, ao analisar as variáveis, identificamos que algumas variáveis listadas como string, seguem o padrão de sim ou não, 1 e 0, portanto deveriam ser tratadas como booleano, como:

- SeniorCitizen (Consideraremos 1 como sim e 0 como não)
- Gender
- Partner
- PhoneService (Precisa padronizar o sim e o não)
- PaperlessBilling
- Churn

Adicionalmente, algumas variáveis deveriam ser categóricas, como:
- InternetService
- MultipleLines 
- OnlineSecurity 
- StreamingTV 
- StreamingMovies
- Contract
- PaymentMethod

- Agora vamos transformar a tabela analisada para o tratamento posterior na camada silver!

In [12]:
df.to_csv("../Data/Bronze/tabela_bronze.csv", index=False, encoding='utf-8-sig')