In [3]:
!pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (2.5.3)
Requirement already satisfied: pandas>=1.2 in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.0.6)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.66.1-cp314-cp314-win_amd64.whl.metadata (132 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in C:\Users\Ana_Lucia\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Collecting pillow>=9 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Ana_Lucia\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.2->seaborn) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\Ana_Lucia\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.5 MB 6.0 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.5 MB 5.7 MB/s eta 0:00:02
   -------------- ------------------------- 3.4/9.5 MB 5.7 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.5 MB 5.7 MB/s eta 0:00:01
   ------------------------ --------------- 5.8/9.5 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 6.3/9.5 MB 5.1 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.5 MB 5.0 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.5 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 8.1/9.5 MB 4.3 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 4.3 MB/s  0:00:02
Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl (240 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.66.1-cp314-cp314-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ------------ --------------------------- 0.8/2.5 MB 5.0 MB/s eta 0:00:01
   ----------------------------- ---------- 1.8/2.5 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 4.9 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl (72 kB)
Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/8 [pyparsing]
   ---------------------------------------- 0/8 [pyparsing]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ---------- ----------------------------- 2/8 [kiwisolver]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.66.1 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-12.3.0 pyparsing-3.3.3 seaborn-0.13.2

In [4]:
!pip install matplotlib

Requirement already satisfied: matplotlib in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (2.5.3)
Requirement already satisfied: packaging>=20.0 in C:\Users\Ana_Lucia\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\Ana_Lucia\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Ana_Lucia\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\Ana_Lucia\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [11]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

### Camada Bronze: dados brutos ingeridos a partir do arquivo history.csv

#### Descrição das variáveis contidas no conjunto de dados

- **CustomerID (ID_Cliente)**: Identificador único de cada cliente

- **Gender (Gênero)**: ndica o gênero do cliente, podendo assumir os valores Masculino (Male) ou Feminino (Female).

- **SeniorCitizen (Idoso)**: Indica se o cliente é ou não uma pessoa idosa. O valor 0 representa que não é idoso e 1 representa que é idoso.

- **Partner (Cônjuge)**: Indica se o cliente possui cônjuge ou parceiro. Pode assumir os valores Sim (Yes) ou Não (No).

- **Dependents (Dependentes)**: Indica se o cliente possui dependentes. Pode assumir os valores Sim (Yes) ou Não (No).

- **Tenure (Tempo_Assinatura)**: Representa o tempo, em meses, que o cliente permanece como assinante do serviço.

- **PhoneService (Servico_Telefonia)**: Indica se o cliente possui serviço de telefonia. Pode assumir os valores Sim (Yes) ou Não (No).

- **MultipleLines (Varias_Linhas)**: Indica se o cliente possui mais de uma linha telefônica. Pode apresentar as opções Sim (Yes), Não (No) ou Sem serviço de telefonia (No phone service).

- **InternetService (Servico_Internet)**: Indica o tipo de serviço de internet utilizado pelo cliente. As categorias presentes na base são DSL, Fibra óptica (Fiber optic) e Sem serviço de internet (No).

- **OnlineSecurity (Seguranca_Online)**: Indica se o cliente possui o serviço de segurança online. Pode apresentar Sim (Yes), Não (No) ou Sem serviço de internet (No internet service).

- **OnlineBackup (Backup_Online)**: Indica se o cliente possui serviço de backup online. Pode apresentar Sim (Yes), Não (No) ou Sem serviço de internet (No internet service).

- **DeviceProtection (Protecao_Dispositivos)**: Indica se o cliente possui proteção para seus dispositivos. Pode apresentar Sim (Yes), Não (No) ou Sem serviço de internet (No internet service).
- **TechSupport (Suporte_Tecnico)**: Indica se o cliente possui serviço de suporte técnico. Pode apresentar Sim (Yes), Não (No) ou Sem serviço de internet (No internet service).
- **StreamingTV (Streaming_TV)**: Indica se o cliente utiliza o serviço de streaming de televisão. Pode apresentar Sim (Yes), Não (No) ou Sem serviço de internet (No internet service).

- **StreamingMovies (Streaming_Filmes)**: Indica se o cliente utiliza o serviço de streaming de filmes. Pode apresentar Sim (Yes), Não (No) ou Sem serviço de internet (No internet service).

- **Contract (Contrato)**: Indica o tipo de contrato firmado pelo cliente. As categorias são Mensal (Month-to-month), Um ano (One year) e Dois anos (Two year).

- **PaperlessBilling (Faturamento_Eletronico)**: Indica se o cliente utiliza faturamento eletrônico, sem o recebimento de fatura impressa. Pode assumir os valores Sim (Yes) ou Não (No).
- **PaymentMethod (Forma_Pagamento)**: Indica a forma utilizada pelo cliente para realizar os pagamentos. As opções incluem Cheque eletrônico (Electronic check), Cheque enviado pelo correio (Mailed check), Transferência bancária (Bank transfer) e Cartão de crédito (Credit card).

- **MonthlyCharges (Valores_Mensais)**: Representa o valor cobrado mensalmente do cliente pelo serviço contratado.

- **TotalCharges (Valores_Totais)**: Representa o valor total cobrado do cliente durante o período em que ele permaneceu como assinante.

- **Churn (Status_Cancelamento)**: Indica se o cliente cancelou ou não o serviço. Yes representa que o cliente cancelou o serviço e No representa que permaneceu como cliente.

- **CustomerFeedbackChurn (Feedback_Cliente)**: Contém um texto com a opinião ou experiência relatada pelo cliente em relação ao serviço, incluindo aspectos como qualidade da internet, preço, forma de pagamento e satisfação geral.

- **MonthlyIncome (Renda_Mensal)**: Representa a renda mensal do cliente.

In [5]:
# Import bibliotecas

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Exibe todas as colunas
pd.set_option('display.max_columns', None)

In [21]:
# Carregar o arquivo CSV com separador de ponto e vírgula
df = pd.read_csv('history.xlsx', sep=';', encoding='utf-8')

# Exibir as primeiras 10 linhas 
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,Yes,Yes,Yes,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532.0
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634.0
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628.0
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851.0
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691.0

In [22]:
# Verificando a dimensão do conjunto de dados
df.shape

(5912, 23)

In [23]:
# Informações dos tipos de variáveis
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5912 entries, 0 to 5911
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5773 non-null   str
 1   gender            5768 non-null   str
 2   SeniorCitizen     5747 non-null   str
 3   Partner           5687 non-null   str
 4   Dependents        5644 non-null   str
 5   tenure            5637 non-null   str
 6   PhoneService      5635 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5549 non-null   float64
dtypes: float64(3), str(20)
memory usage: 1.0 MB

In [24]:
# Verificando se existe valores nulos
df.isnull().sum()

customerID          139
gender              144
SeniorCitizen       165
Partner             225
Dependents          268
tenure              275
PhoneService        277
MultipleLines       278
InternetService     278
OnlineSecurity      278
OnlineBackup        278
DeviceProtection    278
TechSupport         278
StreamingTV         278
StreamingMovies     278
Contract            278
PaperlessBilling    278
PaymentMethod       278
MonthlyCharges      278
TotalCharges        556
Churn               278
CustomerFeedback    278
MonthlyIncome       363
dtype: int64

In [25]:
# Verificar a quantidade total de valores nulos
df.isnull().sum().sum()

np.int64(6304)

In [28]:
# Verificar o percentual de valores nulos em relação ao total de registros
(df.isnull().sum().sum() / len(df)) * 100

np.float64(106.63058186738836)

In [ ]:
# Tabela com o total e a porcentagem de nulos por coluna
tabela_nulos = pd.DataFrame({
    'Total Nulos': df.isnull().sum(),
    'Porcentagem (%)': (df.isnull().sum() / len(df)) * 100
})

# Exibir todas as colunas/linhas 
pd.set_option('display.max_rows', None)

tabela_nulos

                  Total Nulos  Porcentagem (%)
customerID                139         2.351150
gender                    144         2.435724
SeniorCitizen             165         2.790934
Partner                   225         3.805819
Dependents                268         4.533153
tenure                    275         4.651556
PhoneService              277         4.685386
MultipleLines             278         4.702300
InternetService           278         4.702300
OnlineSecurity            278         4.702300
OnlineBackup              278         4.702300
DeviceProtection          278         4.702300
TechSupport               278         4.702300
StreamingTV               278         4.702300
StreamingMovies           278         4.702300
Contract                  278         4.702300
PaperlessBilling          278         4.702300
PaymentMethod             278         4.702300
MonthlyCharges            278         4.702300
TotalCharges              556         9.404601
Churn                     278         4.702300
CustomerFeedback          278         4.702300
MonthlyIncome             363         6.140054

### Camada Silver: dados limpos, filtrados, padronizados e com os devidos tratamentos aplicados.

In [39]:
# Transformar a coluna 'tenure'  e a colu a SeniorCitizen para o tipo inteiro
df["tenure"] = pd.to_numeric(df["tenure"], errors="coerce").astype("Int64")
df["SeniorCitizen"] = pd.to_numeric(df["SeniorCitizen"], errors="coerce").astype("Int64")

In [40]:
# Verificando se foi feito a trasnformação da coluna 'tenure' e 'SeniorCitizen' para o tipo inteiro
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5912 entries, 0 to 5911
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5773 non-null   str
 1   gender            5768 non-null   str
 2   SeniorCitizen     5676 non-null   Int64
 3   Partner           5687 non-null   str
 4   Dependents        5644 non-null   str
 5   tenure            5617 non-null   Int64
 6   PhoneService      5635 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5549 non-null   float64
dtypes: Int64(2), float64(3), str(18)
memory usage: 1.0 MB

In [ ]:
# Verificar os 10 valores nulos na coluna MonthlyCharges

df[df['MonthlyCharges'].isnull()].head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
57,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,However,I do wish that they offered internet service ...,<NA>,so I am glad that this company accommodates t...,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Overall,I am satisfied with the service and have no c...,7349,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,I appreciate the convenience of being able to ...,as it makes managing my account much easier. ...,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Overall,I have had a positive experience with this in...,5341,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,The only downside for me is that they do not o...,which is something I would have liked to have...,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Camada Gold: dados agregados e modelados, prontos para análises de negócios e consultas de lata performance.